version: '2'
services:
  mongo-data-rest:
    image: lab1/mongo-data-rest
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  mongodb:
    build: ../../docker-images/mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - data_mongo:/data/db
volumes:
  data_mongo: